//! postgres_otel_tracing_demo
//!
//! A demo OpenTelemetry exporter for PostgreSQL's contrib/otel.  Loads
//! as a postgres shared-preloaded module, locates contrib/otel's
//! `OtelTracingApi` via the rendezvous variable, registers an emit
//! callback, and ships completed spans through the real
//! `opentelemetry-rust` SDK.
//!
//! Exporter selection follows the OpenTelemetry environment-variable
//! conventions:
//!
//!  * `OTEL_TRACES_EXPORTER`     — `otlp`, `console`/`stdout`/`logging`,
//!                                 or `none`.  Default: `stdout`.
//!  * `OTEL_EXPORTER_OTLP_ENDPOINT`,
//!    `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT`,
//!    `OTEL_EXPORTER_OTLP_HEADERS`,
//!    `OTEL_EXPORTER_OTLP_TIMEOUT`,
//!    `OTEL_EXPORTER_OTLP_PROTOCOL` — picked up by the otlp exporter.
//!  * `OTEL_SERVICE_NAME`,
//!    `OTEL_RESOURCE_ATTRIBUTES`   — Resource attrs (via the SDK's
//!                                   EnvResourceDetector).
//!
//! Note: contrib/otel itself owns sampling decisions (via its own
//! sampler hook and `otel.trace_all_queries` GUC).  By the time a
//! span reaches us via the emit hook, it has already been sampled
//! in.  `OTEL_TRACES_SAMPLER` is therefore NOT honoured here; this
//! exporter is downstream of the sampler decision.

#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals, dead_code)]

// Generated by build.rs from <otel/otel.h>.
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

use once_cell::sync::OnceCell;
use opentelemetry::{
    trace::{SpanContext, SpanId, SpanKind, Status, TraceFlags, TraceId, TraceState},
    InstrumentationScope, Key, KeyValue,
};
use opentelemetry_sdk::{
    export::trace::SpanData,
    resource::{EnvResourceDetector, ResourceDetector, TelemetryResourceDetector},
    runtime::TokioCurrentThread,
    trace::{BatchSpanProcessor, SpanEvents, SpanLinks, SpanProcessor},
    Resource,
};
use std::borrow::Cow;
use std::ffi::CStr;
use std::os::raw::{c_char, c_int};
use std::panic::catch_unwind;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

// ---- PG_MODULE_MAGIC, pure Rust ----------------------------------
//
// Postgres' dlopen path calls dlsym("Pg_magic_func") on the module
// and expects a Pg_magic_struct describing the ABI version it was
// built against.  The canonical way to produce this is the
// PG_MODULE_MAGIC macro in C; pgrx reproduces it in pure Rust by
// reading the postgres constants from bindgen and emitting the
// struct as a Rust static.  Same trick here.
//
// The struct fields and their sources (all from
// `$(pg_config --includedir-server)`, allowlisted in build.rs):
//
//   version       PG_VERSION_NUM / 100
//   funcmaxargs   FUNC_MAX_ARGS         (pg_config_manual.h)
//   indexmaxkeys  INDEX_MAX_KEYS        (pg_config_manual.h)
//   namedatalen   NAMEDATALEN           (pg_config_manual.h)
//   float8byval   FLOAT8PASSBYVAL       (c.h)
//   abi_extra     FMGR_ABI_EXTRA        (pg_config_manual.h)
//
// The const-fn dance below is just for filling the fixed-size
// abi_extra char array at compile time --- FMGR_ABI_EXTRA is a
// NUL-terminated string literal and abi_extra is [c_char; 32].

const fn abi_extra_array() -> [c_char; 32] {
    let mut arr = [0 as c_char; 32];
    let src: &[u8] = FMGR_ABI_EXTRA;
    let mut i = 0;
    while i < src.len() && i < arr.len() {
        arr[i] = src[i] as c_char;
        i += 1;
    }
    arr
}

// Pg_magic_struct contains *const c_char fields (name, version) and
// thus isn't Send/Sync.  But we only ever read it, never write, and
// the values we put in are null pointers or pointers into rodata.
// Wrap in a #[repr(transparent)] newtype with an unsafe Sync impl,
// the same pattern pgrx uses (their AssertSync<Pg_magic_struct>).
#[repr(transparent)]
struct AssertSync<T>(T);
unsafe impl<T> Sync for AssertSync<T> {}

static PG_MAGIC_DATA: AssertSync<Pg_magic_struct> = AssertSync(Pg_magic_struct {
    len: std::mem::size_of::<Pg_magic_struct>() as c_int,
    abi_fields: Pg_abi_values {
        version: (PG_VERSION_NUM / 100) as c_int,
        funcmaxargs: FUNC_MAX_ARGS as c_int,
        indexmaxkeys: INDEX_MAX_KEYS as c_int,
        namedatalen: NAMEDATALEN as c_int,
        float8byval: FLOAT8PASSBYVAL as c_int,
        abi_extra: abi_extra_array(),
    },
    name: std::ptr::null(),
    version: std::ptr::null(),
});

#[no_mangle]
pub extern "C" fn Pg_magic_func() -> *const Pg_magic_struct {
    &PG_MAGIC_DATA.0
}

// ---- FFI conveniences --------------------------------------------

/// PostgreSQL's epoch is 2000-01-01 UTC; TimestampTz is microseconds
/// since that instant.  946684800 = unix seconds at 2000-01-01 UTC.
const PG_EPOCH_UNIX_SECS: i64 = 946_684_800;

// ---- Per-backend state -------------------------------------------
//
// CRITICAL: _PG_init runs in the postmaster, but the SDK's
// BatchSpanProcessor spawns a worker thread, and threads do NOT
// survive fork().  If we built the processor in _PG_init, every
// backend would end up holding the sender half of a channel whose
// receiver thread was lost at fork --- on_end would silently
// succeed (the channel is unbounded-ish) and nothing would ever
// export.
//
// Therefore the postmaster-side _PG_init only:
//   (a) locates contrib/otel's api and version-checks it
//   (b) registers our emit hook in the api
//
// All SDK construction happens lazily in the emit hook, inside
// each backend process, via thread_local!.  Per-backend overhead
// is one worker thread + one exporter connection, which matches
// the postgres process model.
struct BackendState {
    processor: BatchSpanProcessor<TokioCurrentThread>,
    instrumentation_scope: InstrumentationScope,
    resource: Resource,
}

/// Prev-hook for chaining.  Set once in _PG_init (postmaster).
static PREV_EMIT: OnceCell<otel_span_emit_hook_type> = OnceCell::new();

/// Cached exporter-kind decision (env-var look-up done once in
/// _PG_init; backends just consult the result).
static EXPORTER_KIND: OnceCell<ExporterKind> = OnceCell::new();

#[derive(Copy, Clone)]
enum ExporterKind {
    None,
    Stdout,
    Otlp,
}

// ---- Module entrypoint -------------------------------------------

#[no_mangle]
pub unsafe extern "C" fn _PG_init() {
    let _ = catch_unwind(|| {
        if let Err(e) = init_inner() {
            eprintln!("postgres_otel_tracing_demo: init failed: {e}");
        }
    });
}

unsafe fn init_inner() -> Result<(), Box<dyn std::error::Error>> {
    // 1. Locate contrib/otel's rendezvous-published api.
    let rendezvous_name = CStr::from_bytes_with_nul(OTEL_TRACING_API_RENDEZVOUS_NAME)?;
    let slot = find_rendezvous_variable(rendezvous_name.as_ptr());
    if slot.is_null() {
        return Err("find_rendezvous_variable returned NULL".into());
    }
    let api_ptr = *slot as *const OtelTracingApi;
    if api_ptr.is_null() {
        return Err(
            "OtelTracingApi not installed; add 'otel' before this module in shared_preload_libraries".into(),
        );
    }
    let api = &*api_ptr;
    if api.version != OTEL_TRACING_API_VERSION {
        return Err(format!(
            "OtelTracingApi version mismatch: loaded={}, built-against={}",
            api.version, OTEL_TRACING_API_VERSION
        )
        .into());
    }

    // 2. Decide on an exporter kind from the env var now (cheap), so
    //    each backend doesn't re-parse it.
    let kind_str = std::env::var("OTEL_TRACES_EXPORTER")
        .unwrap_or_else(|_| "stdout".into())
        .to_lowercase();
    let kind = match kind_str.as_str() {
        "none" => ExporterKind::None,
        "otlp" => ExporterKind::Otlp,
        _ => ExporterKind::Stdout, // stdout/console/logging/anything else
    };
    EXPORTER_KIND.set(kind).ok();
    if matches!(kind, ExporterKind::None) {
        eprintln!("postgres_otel_tracing_demo: OTEL_TRACES_EXPORTER=none; not registering");
        return Ok(());
    }

    // 3. Register the emit hook.  All SDK construction is deferred to
    //    the backend (see emit_hook + ensure_backend) because threads
    //    don't survive fork().
    let mut prev_out: otel_span_emit_hook_type = None;
    let register = api
        .register_emit_hook
        .ok_or("OtelTracingApi.register_emit_hook is null")?;
    register(Some(emit_hook), &mut prev_out);
    PREV_EMIT.set(prev_out).ok();

    Ok(())
}

/// Lazily build the backend-local SDK state on first emit in this
/// process.  Returns None if construction fails; subsequent emits
/// in the same backend re-attempt (cheap path: just consulting the
/// thread_local OnceCell).
///
/// CRITICAL: this must NEVER run in the postmaster.  Threads inside
/// BatchSpanProcessor's worker do not survive fork(); a state built
/// in the postmaster would have a dead receiver in every backend.
/// Calling this from emit_hook (which only runs in backends, since
/// contrib/otel doesn't emit spans in the postmaster) is safe.
fn ensure_backend() -> Option<&'static BackendState> {
    if let Some(s) = BACKEND_CACHE.with(|c| c.get()) {
        return Some(s);
    }

    let kind = *EXPORTER_KIND.get()?;
    let state = build_backend_state(kind).ok()?;
    // Box::leak: we want a 'static reference so the on_proc_exit
    // callback can reach it without lifetime fuss.  The backend
    // process exits when this state is no longer needed, so a leak
    // costs nothing (the whole address space gets reclaimed).
    let leaked: &'static BackendState = Box::leak(Box::new(state));
    BACKEND_CACHE.with(|c| c.set(Some(leaked)));
    Some(leaked)
}

fn build_backend_state(kind: ExporterKind) -> Result<BackendState, Box<dyn std::error::Error>> {
    // Build a Resource: env-driven, with a "postgres" service.name
    // fallback when env vars didn't supply one.  Skip
    // SdkProvidedResourceDetector because its "unknown_service"
    // would otherwise shadow the "postgres" default.
    let env_resource = Resource::from_detectors(
        Duration::from_secs(0),
        vec![
            Box::new(TelemetryResourceDetector) as Box<dyn ResourceDetector>,
            Box::new(EnvResourceDetector::new()) as Box<dyn ResourceDetector>,
        ],
    );
    let resource = if env_resource.get(Key::new("service.name")).is_some() {
        env_resource
    } else {
        Resource::new([KeyValue::new("service.name", "postgres")]).merge(&env_resource)
    };

    let mut processor: BatchSpanProcessor<TokioCurrentThread> = match kind {
        ExporterKind::None => return Err("ExporterKind::None reached build_backend_state".into()),
        ExporterKind::Otlp => {
            let exporter = opentelemetry_otlp::SpanExporter::builder()
                .with_tonic()
                .build()?;
            BatchSpanProcessor::builder(exporter, TokioCurrentThread).build()
        }
        ExporterKind::Stdout => {
            let exporter = opentelemetry_stdout::SpanExporter::default();
            BatchSpanProcessor::builder(exporter, TokioCurrentThread).build()
        }
    };
    processor.set_resource(&resource);

    let instrumentation_scope = InstrumentationScope::builder("postgres_otel_tracing_demo")
        .with_version(env!("CARGO_PKG_VERSION"))
        .build();

    Ok(BackendState {
        processor,
        instrumentation_scope,
        resource,
    })
}

// ---- Span emit hook ----------------------------------------------

unsafe extern "C" fn emit_hook(span_ptr: *const OtelSpan) {
    let _ = catch_unwind(|| {
        if span_ptr.is_null() {
            return;
        }
        if let Some(state) = ensure_backend() {
            let data = translate(state, &*span_ptr);
            state.processor.on_end(data);
            // Side-effect of ensure_backend's first call: register
            // an on_proc_exit hook that force-flushes + shuts down
            // the processor when the backend exits.  Without this,
            // BatchSpanProcessor's last batch (anything emitted in
            // the final BATCH_TIMEOUT window) would be lost when the
            // worker thread gets killed at process exit.
            ensure_shutdown_registered();
        }
    });

    if let Some(Some(prev)) = PREV_EMIT.get() {
        prev(span_ptr);
    }
}

// ---- on_proc_exit shutdown ---------------------------------------

unsafe extern "C" {
    fn on_proc_exit(
        function: unsafe extern "C" fn(code: c_int, arg: usize),
        arg: usize,
    );
}

thread_local! {
    static SHUTDOWN_REGISTERED: std::cell::Cell<bool> = const { std::cell::Cell::new(false) };
}

fn ensure_shutdown_registered() {
    SHUTDOWN_REGISTERED.with(|c| {
        if c.get() {
            return;
        }
        c.set(true);
        unsafe { on_proc_exit(proc_exit_cb, 0) };
    });
}

unsafe extern "C" fn proc_exit_cb(_code: c_int, _arg: usize) {
    // catch_unwind: a panic crossing back into postgres' on_proc_exit
    // chain would terminate the cleanup of every later-registered
    // callback.  Always swallow.
    let _ = catch_unwind(|| {
        // peek_backend (not ensure_backend) --- shutdown time is the
        // wrong moment to lazily build a processor we'd immediately
        // tear down.
        if let Some(state) = BACKEND_CACHE.with(|c| c.get()) {
            let _ = state.processor.force_flush();
            let _ = state.processor.shutdown();
        }
    });
}

thread_local! {
    static BACKEND_CACHE: std::cell::Cell<Option<&'static BackendState>> = const { std::cell::Cell::new(None) };
}

// ---- OtelSpan -> SpanData translation ----------------------------

fn translate(state: &BackendState, c: &OtelSpan) -> SpanData {
    let trace_id = parse_trace_id(&c.trace_id);
    let span_id = parse_span_id(&c.span_id);
    let parent_span_id = parse_span_id(&c.parent_span_id);
    let trace_state_str = unsafe { c_str_or_empty(c.tracestate) };
    let trace_state =
        TraceState::from_key_value(parse_tracestate(&trace_state_str)).unwrap_or_default();

    // BatchSpanProcessor::on_end silently drops any span whose
    // SpanContext.is_sampled() returns false.  By the time
    // contrib/otel has called our emit hook, its own sampler has
    // already decided this span should be recorded --- so for the
    // SDK's purposes, sampled must be true.  We preserve any other
    // bits from the propagated W3C flags (none defined as of v1)
    // but force-set the sampled bit.
    let propagated_flags = parse_trace_flags(&c.trace_flags);
    let trace_flags = propagated_flags | TraceFlags::SAMPLED;

    let span_context = SpanContext::new(
        trace_id,
        span_id,
        trace_flags,
        /* is_remote = */ true,
        trace_state,
    );

    let name = unsafe { c_str_or_empty(c.name) };
    let kind = map_kind(c.kind);
    let status = map_status(c.status, unsafe { c_str_or_empty(c.status_description) });

    let attributes = collect_attributes(c);

    // SpanEvents / SpanLinks are #[non_exhaustive] so they can only
    // be built via Default + field assignment.
    let mut events = SpanEvents::default();
    events.events = collect_events(c);

    SpanData {
        span_context,
        parent_span_id,
        span_kind: kind,
        name: Cow::Owned(name),
        start_time: pg_ts_to_systemtime(c.start_time),
        end_time: pg_ts_to_systemtime(c.end_time),
        attributes,
        dropped_attributes_count: 0,
        events,
        links: SpanLinks::default(),
        status,
        instrumentation_scope: state.instrumentation_scope.clone(),
    }
}

unsafe fn c_str_or_empty(p: *const c_char) -> String {
    if p.is_null() {
        return String::new();
    }
    CStr::from_ptr(p).to_string_lossy().into_owned()
}

fn fixed_c_str(arr: &[c_char]) -> String {
    // arr is a fixed-length NUL-terminated char array (e.g.
    // trace_id[33]).  Find the NUL and take everything before.
    let bytes: &[u8] = unsafe { std::slice::from_raw_parts(arr.as_ptr() as *const u8, arr.len()) };
    let n = bytes.iter().position(|&b| b == 0).unwrap_or(arr.len());
    std::str::from_utf8(&bytes[..n])
        .map(|s| s.to_owned())
        .unwrap_or_default()
}

fn parse_trace_id(arr: &[c_char]) -> TraceId {
    TraceId::from_hex(&fixed_c_str(arr)).unwrap_or(TraceId::INVALID)
}

fn parse_span_id(arr: &[c_char]) -> SpanId {
    SpanId::from_hex(&fixed_c_str(arr)).unwrap_or(SpanId::INVALID)
}

fn parse_trace_flags(arr: &[c_char]) -> TraceFlags {
    let s = fixed_c_str(arr);
    let b = u8::from_str_radix(&s, 16).unwrap_or(0);
    TraceFlags::new(b)
}

fn parse_tracestate(s: &str) -> Vec<(String, String)> {
    if s.is_empty() {
        return Vec::new();
    }
    s.split(',')
        .filter_map(|kv| {
            let mut it = kv.splitn(2, '=');
            let k = it.next()?.trim().to_owned();
            let v = it.next()?.trim().to_owned();
            if k.is_empty() {
                None
            } else {
                Some((k, v))
            }
        })
        .collect()
}

fn map_kind(k: OtelSpanKind) -> SpanKind {
    match k {
        v if v == OtelSpanKind_OTEL_SPAN_KIND_SERVER => SpanKind::Server,
        v if v == OtelSpanKind_OTEL_SPAN_KIND_CLIENT => SpanKind::Client,
        v if v == OtelSpanKind_OTEL_SPAN_KIND_PRODUCER => SpanKind::Producer,
        v if v == OtelSpanKind_OTEL_SPAN_KIND_CONSUMER => SpanKind::Consumer,
        _ => SpanKind::Internal,
    }
}

fn map_status(s: OtelSpanStatus, description: String) -> Status {
    match s {
        v if v == OtelSpanStatus_OTEL_STATUS_OK => Status::Ok,
        v if v == OtelSpanStatus_OTEL_STATUS_ERROR => Status::Error {
            description: Cow::Owned(description),
        },
        _ => Status::Unset,
    }
}

fn pg_ts_to_systemtime(ts: i64) -> SystemTime {
    let secs = ts.div_euclid(1_000_000) + PG_EPOCH_UNIX_SECS;
    let nanos = (ts.rem_euclid(1_000_000) * 1_000) as u32;
    if secs < 0 {
        return UNIX_EPOCH;
    }
    UNIX_EPOCH + Duration::new(secs as u64, nanos)
}

fn collect_attributes(c: &OtelSpan) -> Vec<KeyValue> {
    let mut out = Vec::with_capacity((c.n_attrs as usize) + (c.n_overflow_attrs as usize));
    push_kv_array(&c.attrs, c.n_attrs, &mut out);
    if !c.overflow_attrs.is_null() && c.n_overflow_attrs > 0 {
        let slice =
            unsafe { std::slice::from_raw_parts(c.overflow_attrs, c.n_overflow_attrs as usize) };
        push_kv_array(slice, c.n_overflow_attrs, &mut out);
    }
    out
}

fn push_kv_array(arr: &[OtelKeyValue], n: c_int, out: &mut Vec<KeyValue>) {
    for i in 0..n as usize {
        if i >= arr.len() {
            break;
        }
        let kv = &arr[i];
        if kv.key.is_null() {
            continue;
        }
        let key = unsafe { c_str_or_empty(kv.key) };
        let value = unsafe { c_str_or_empty(kv.value) };
        if key.is_empty() {
            continue;
        }
        out.push(KeyValue::new(key, value));
    }
}

fn collect_events(c: &OtelSpan) -> Vec<opentelemetry::trace::Event> {
    let mut out = Vec::new();
    if c.inline_event_used {
        out.push(translate_event(&c.inline_event));
    }
    if !c.overflow_events.is_null() && c.n_overflow_events > 0 {
        let slice =
            unsafe { std::slice::from_raw_parts(c.overflow_events, c.n_overflow_events as usize) };
        for e in slice {
            out.push(translate_event(e));
        }
    }
    out
}

fn translate_event(e: &OtelSpanEvent) -> opentelemetry::trace::Event {
    let core = &e.core;
    let msg = unsafe { c_str_or_empty(e.message) };
    let mut attrs: Vec<KeyValue> = Vec::new();

    // SQLSTATE is by-value (5 chars + NUL) in the C struct.
    let sqlstate_bytes: &[u8] = unsafe {
        std::slice::from_raw_parts(core.sqlstate.as_ptr() as *const u8, core.sqlstate.len())
    };
    let nul_at = sqlstate_bytes.iter().position(|&b| b == 0).unwrap_or(0);
    if nul_at > 0 {
        if let Ok(s) = std::str::from_utf8(&sqlstate_bytes[..nul_at]) {
            attrs.push(KeyValue::new("postgres.sqlstate", s.to_owned()));
        }
    }
    attrs.push(KeyValue::new("postgres.elevel", core.elevel as i64));

    if !core.filename.is_null() {
        attrs.push(KeyValue::new("code.filepath", unsafe {
            c_str_or_empty(core.filename)
        }));
    }
    attrs.push(KeyValue::new("code.lineno", core.lineno as i64));
    if !core.funcname.is_null() {
        attrs.push(KeyValue::new("code.function", unsafe {
            c_str_or_empty(core.funcname)
        }));
    }

    if !e.detail.is_null() {
        attrs.push(KeyValue::new("postgres.detail", unsafe {
            c_str_or_empty(e.detail)
        }));
    }
    if !e.hint.is_null() {
        attrs.push(KeyValue::new("postgres.hint", unsafe {
            c_str_or_empty(e.hint)
        }));
    }

    if !e.attrs.is_null() && e.n_attrs > 0 {
        let slice = unsafe { std::slice::from_raw_parts(e.attrs, e.n_attrs as usize) };
        push_kv_array(slice, e.n_attrs, &mut attrs);
    }

    opentelemetry::trace::Event::new(msg, pg_ts_to_systemtime(core.time), attrs, 0)
}
